# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.4
yarn_mappings=1.21.4+build.8
loader_version=0.17.2
loom_version=1.11-SNAPSHOT

# Mod Properties
mod_version=1.0.4
maven_group=com.whyvo.dine
archives_base_name=dine

# Dependencies
fabric_version=0.119.4+1.21.4


systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=7890
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=7890
systemProp.socksProxyHost=127.0.0.1
systemProp.socksProxyPort=7890
